package moonlight.ws.base.health;

public interface HealthCheck {

	/**
	 * Name of the virtual health-check summarizing all health-checks into a total
	 * result. Total health is good, if all health-statuses (from all checks) are
	 * good. As soon as there is at least one malady, the total health is considered
	 * sick.
	 */
	String NAME_ALL = "_all_";

	String getName();

	/**
	 * Checks the health of the sub-system this implementation is responsible for.
	 *
	 * @return the status of the sub-system's health. If the sub-system is healthy,
	 *         this method returns either {@code null} or an instance of
	 *         {@code HealthStatus} with {@link HealthStatus#getMaladyCode()
	 *         maladyCode} being {@code null} or empty. A non-empty
	 *         {@code maladyCode} indicates a health-problem.
	 *
	 * @throws Exception if the sub-system is very unhealthy. In this case, the
	 *                   {@code maladyCode} is generated by the framework (usually
	 *                   containing the exception's class-name, but this may change
	 *                   any time without notice).
	 */
	HealthStatus check() throws Exception;
}
