package moonlight.ws.liferay;

public enum OrderStatus {

	COMPLETED, // 0
	PENDING, // 1
	OPEN, // 2
	UNDEFINED3, UNDEFINED4, UNDEFINED5, //
	IN_PROGRESS, // 6
	UNDEFINED7, //
	CANCELED, // 8
	UNDEFINED9, // 9
	PROCESSING, // 10
	UNDEFINED11, UNDEFINED12, UNDEFINED13, //
	PARTIALLY_SHIPPED, // 14
	SHIPPED, // 15
	UNDEFINED16, UNDEFINED17, UNDEFINED18, UNDEFINED19, //
	ON_HOLD, // 20
	QUOTE_REQUESTED, // 21
	QUOTE_PROCESSED // 22

}
